<?php

namespace App\Repository;

use App\Entity\Article;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping;


/**
 * ArticleRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function __construct($em, Mapping\ClassMetadata $class)
    {
        parent::__construct($em, $class);
    }

    public function findSimilarSell(Article $article)
    {
        $sql = 'SELECT COUNT(article.label) as total, article.label as articleLabel, article.id FROM article RIGHT JOIN command_details on article.id = command_details.product_id RIGHT JOIN command c on command_details.command_id = c.id WHERE c.id IN(SELECT command_id FROM command_details WHERE c.id IN (SELECT command_id FROM command_details GROUP BY command_id HAVING COUNT(*) > :id) AND product_id = :id) AND article.id Not like :id GROUP BY articleLabel LIMIT 0,2';

        $stmt = $this->_em->getConnection()->prepare($sql);
        $stmt->bindValue('id', $article->getId());
        $stmt->execute();

        return $stmt->fetchAll();
    }
}
